"""Shared rendering helpers for professor profile slots across site surfaces."""
from __future__ import annotations

import hashlib
import html
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = ROOT / "tools" / "fronts" / "data"
PROFILE_DATA = DATA_DIR / "professors.json"


def _hash(path: Path) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()[:10]


def name_slot(course: str, label: str, root_prefix: str, open_: bool = False) -> str:
    """Return a text-first slot; JS upgrades it to a button only for known profiles."""
    opened = ' data-professor-open="true"' if open_ else ""
    return (f'<span class="professor-fallback" data-professor-course="{html.escape(course, quote=True)}" '
            f'data-professor-root="{html.escape(root_prefix, quote=True)}"{opened}>{html.escape(label)}</span>')


def stylesheet_link(root_prefix: str) -> str:
    css = ROOT / "assets" / "professor-card.css"
    return f'<link rel="stylesheet" href="{root_prefix}assets/professor-card.css?v={_hash(css)}">'


def script_tags(root_prefix: str) -> str:
    data = ROOT / "assets" / "professors-data.js"
    runtime = ROOT / "assets" / "professor-card.js"
    return (
        f'<script src="{root_prefix}assets/professors-data.js?v={_hash(data)}" defer></script>\n'
        f'<script src="{root_prefix}assets/professor-card.js?v={_hash(runtime)}" defer></script>'
    )


def asset_links(root_prefix: str) -> str:
    """Shared CSS and data/runtime scripts with content hashes for cache busting."""
    return stylesheet_link(root_prefix) + "\n" + script_tags(root_prefix)


def public_profiles() -> dict[str, dict[str, Any]]:
    """Build browser data from source JSON, omitting sources and check dates."""
    profiles = json.loads(PROFILE_DATA.read_text(encoding="utf-8"))
    courses: dict[str, dict[str, str]] = {}
    for path in DATA_DIR.glob("*.json"):
        if path.name == "professors.json":
            continue
        row = json.loads(path.read_text(encoding="utf-8"))
        slug = path.stem
        courses[slug] = {
            "title": row.get("title", slug),
            "href": f"courses/{slug}/index.html",
        }
    public: dict[str, dict[str, Any]] = {}
    for profile in profiles:
        teaching = [courses[slug] | {"slug": slug}
                    for slug in profile.get("courses", []) if slug in courses]
        safe_profile = {
            "name": profile["name"],
            "title": profile["title"],
            "bio": profile["bio"],
            "courses": teaching,
        }
        for course in profile.get("courses", []):
            if course in courses:
                public[course] = safe_profile
    return public


def public_data_script() -> str:
    payload = json.dumps(public_profiles(), ensure_ascii=False, separators=(",", ":"))
    return "/* Generated by tools/professors.py from tools/fronts/data/professors.json. */\n" \
        f"window.ordenacoesProfessorProfiles={payload};\n"


def professor_label(course: str) -> str:
    """Read the course's current professor label, including unprofiled instructors."""
    path = DATA_DIR / f"{course}.json"
    if not path.exists():
        return "Professor"
    data = json.loads(path.read_text(encoding="utf-8"))
    return str(data.get("prof") or "Professor")
